### ISSUE TITLE
"additionalItems" should not be honored if "items" is an object.

### ISSUE THREAD

**Issue by SereneAnt** [jsonrainbow/json-schema#333] opened 2016-11-08 14:44 UTC
As per [json-schema specification](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.9):
> if "items" is not present, or its value is an object, validation of the instance always succeeds, regardless of the value of "additionalItems";

Currently (v 4.0.x), CollectionConstraint makes an extra checks for "additionalItems" if "items" is object and  fails validation

**Comment by shmax** [comment] 2017-01-29 03:46
Feel free to open a PR

**Comment by erayd** [comment] 2017-04-11 07:31
@SereneAnt @shmax Are either of you guys intending to address this, or should I add it to my list?

**Comment by erayd** [comment] 2017-04-11 07:31
(Note that I don't consider this a high priority, so if it goes on my list, it may take me a while to get to it).

**Comment by SereneAnt** [comment] 2017-04-11 20:26
@erayd I'm off this train as for now, sorry. For sure, you'll do it better!

**Comment by shmax** [comment] 2017-04-13 04:32
@erayd I wasn't planning on it, but you've been doing most of the heavy labor around here lately, so if you would like me to look at it I will.

**Comment by erayd** [comment] 2017-04-13 07:07
@shmax Feel free if you're in the mood, but no pressure and no rush - this issue is IMO minor, has already been open for five months, and the OP doesn't seem to care.

If you don't feel like doing this, it's not an issue, and I'll probably catch is sometime during my implementation of strict-mode, once we have the rules thing sorted.

**Comment by DannyvdSluijs** [comment] 2024-09-24 09:09
Unable to reproduce, closing for now. @SereneAnt feel free to reopen with additional information.
Also glancing at the [Bowtie report](https://bowtie.report/#/dialects/draft4?language=php) the test case which seems to be the context you're describing passes (on the V6.0..0 version).
<img width="873" alt="Screenshot 2024-09-24 at 11 07 24" src="https://github.com/user-attachments/assets/2c31cc38-72df-448f-8752-70b10910fb1d">

**Closed by DannyvdSluijs** 2024-09-24 09:09 UTC
Labels: Triage
