### ISSUE TITLE
"Array value found, but an array is required"

### ISSUE THREAD

**Issue by adjenks** [jsonrainbow/json-schema#523] opened 2018-07-18 23:30 UTC
I'm receiving this error message:

>  "Array value found, but an array is required"

I don't quite understand this error. It's saying that a property is an array, but it needs an array. It seems to me like it has what it wants. This error is not intuitive. Can someone explain to me what the library wants?

**Comment by adjenks** [comment] 2018-07-18 23:54
I think I understand what's going on. It's because it is receiving an associative PHP array but it wants an indexed array. It makes it confusing because they are the same 'type' in PHP. You actually have to go through the effort to check if you want to know if something is associative vs indexed in PHP.
See: https://stackoverflow.com/questions/173400/how-to-check-if-php-array-is-associative-or-sequential
So perhaps this library should say:

> " Array (with non-integer keys) value found, but an array is required."

Or something of the sort.

**Comment by shmax** [comment] 2018-07-19 00:12
Can you please provide a (minimal) schema sample that produces this error?

**Comment by adjenks** [comment] 2018-07-19 02:01
Schema (test.json):
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "array",
	"items": {
		"type": "object",
		"patternProperties": {
			".*": {
				"type": "boolean"
			}
		}
	}
}
```
Data:
`{"test":true}`

Code:
```
	$validator->validate(
		json_decode('{"test":true}',1) // Without the "1" it's a bit more clear and says Object
		,(object)['$ref' => 'file://' . realpath('./schemas/test.json')]
		,Constraint::CHECK_MODE_COERCE_TYPES | Constraint::CHECK_MODE_TYPE_CAST // coerce types for the browser.
	);
```

Output:
`{"errors":[{"detail":"Array value found, but an array is required","property":""}]}`

**Comment by erayd** [comment] 2018-07-19 02:31
@adjenks Thanks for that - definitely looks like something we ought to improve on.

Out of curiosity, why are you forcing `json_decode` to use associative arrays instead of objects? It's not the default, and it's an unusual thing to do.

**Comment by adjenks** [comment] 2018-07-19 18:51
I just forced json_decode to use an array to demonstrate the problem when you are already working with an array.

**Comment by antodippo** [comment] 2018-10-30 19:28
Hi @adjenks, I tried to make this test fail:
```
public function testValidateAssociativeArray()
    {
        $value = json_decode('{"test":true}', 1);

        $schema = (object) '
        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "array",
            "items": {
                "type": "object",
                "patternProperties": {
                    ".*": {
                        "type": "boolean"
                    }
                }
            }
        }';

        $validator = new Validator();
        $validator->validate($value, $schema, Constraint::CHECK_MODE_COERCE_TYPES | Constraint::CHECK_MODE_TYPE_CAST);
    }
```
but it doesn't. On which PHP version are you?

**Comment by erayd** [comment] 2018-10-30 20:13
@antodippo You can't cast a string to an object the way you are attempting to do - you just end up with an `StdClass` object containing a single string property, which obviously is not a sane schema.

Use `json_decode()`, not `(object)` casting.

**Comment by erayd** [comment] 2018-10-30 20:15
To clarify - the object that results from using `(object)` on a string is essentially an empty schema, against which any input is considered valid.

**Comment by adjenks** [comment] 2018-10-30 23:02
@antodippo 
I was using whatever the newest PHP version was when I made the post.
erayd is correct, you can't turn a string into an object. PHP tries to but it makes no sense. See this example:

```
php > $a = (object)'{"testing":123}';
php > var_export($a);
stdClass::__set_state(array(
   'scalar' => '{"testing":123}',
))
php > echo $a;
PHP Recoverable fatal error:  Object of class stdClass could not be converted to string in php shell code on line 1

```

**Comment by FabienSalles** [comment] 2019-08-06 11:58
Hi,

I have the same problem : 

```hydra:member[0]: Array value found, but an object is required```

My json is : 

```json
{
   "@id":"\/product_variants",
   "@type":"hydra:Collection",
   "hydra:member":[
      {
         "@id":"\/product_variants\/my_product",
         "@type":"ProductVariant",
         "code":"my_product",
         "position":0,
         "createdAt":"2019-08-05T16:09:13+00:00",
         "updatedAt":null,
         "optionsValues":[
            {
               "@id":"\/product_option_values\/1",
               "code":"age_class_children",
               "optionCode":"age_class",
               "position":0
            },
            {
               "@id":"\/product_option_values\/3",
               "code":"class_ordinary",
               "optionCode":"class",
               "position":1
            },
            {
               "@id":"\/product_option_values\/5",
               "code":"duration_seven",
               "optionCode":"duration",
               "position":2
            }
         ]
      }
   ]
}
```

And my simplified shcema in order to get the error : 

```json
{
  "type": "object",
    "required": [
    "@id",
    "@type",
    "hydra:member"
  ],
 "properties": {
 "hydra:member": {
   "type": "array",
   "items": {
     "type": "object",
     "required": [
       "@id",
       "@type",
       "code",
       "position",
       "createdAt",
        "updatedAt",
        "optionsValues"
       ]
     }
   }
 }
 }
```

How can we validate a collection of object ?

**Comment by DannyvdSluijs** [comment] 2024-09-26 13:39
I've been trying to read up on this issue and try to understand. My summary up until now is
- The original report was made to highlight that under certain circumstances an error message is returned which makes no sense: "Array value found, but an array is required"
- The root cause of the weird error message is due to the forcing of an associative array (a concept unknown in JSON)
- https://github.com/jsonrainbow/json-schema/issues/523#issuecomment-434501449 is a so called Red herring and seemingly has nothing to do with the original report.
- https://github.com/jsonrainbow/json-schema/issues/523#issuecomment-518638712 seems to be another issue by itself. although in `v6.0.0` the JSON is valid as per provided schema. @FabienSalles if you think this is still an issue please open a new issue.

This is caused because the `json_decode` is done using `$associative = true`. This creates an  associative array type which is possible in PHP but isn't possible in JSON. Which leads me to believe the core of the issue is the forcing of an associative array. As already mentioned by @erayd in https://github.com/jsonrainbow/json-schema/issues/523#issuecomment-406135022

@adjenks in https://github.com/jsonrainbow/json-schema/issues/523#issuecomment-406378412 you mention you used `$associative = true` to enforce the array. It is actually the only way you could trigger the issue as there is no valid JSON string to have a associative array in JSON. You can see in below snippet that an associative array is actually an object in JSON
```php
$input = ['test' => true, 'test2' => 3];
echo json_encode($input);

// {"test":true,"test2":3}
```

I'll close the issue for now as the problem is caused by using the `$associative = true` when calling `json_decode` which should not be done as you are actually manipulating the JSON.

If any of the above is unclear or incorrect, feel free to reopen the issue with additional information

**Closed by DannyvdSluijs** 2024-09-26 13:39 UTC

**Comment by adjenks** [comment] 2024-10-09 22:24
Ah, my point was that the data I was using came from another library and it was provided already in associative array format. I'm not setting $associative=true in my real code, I'm not even using json_decode, it was just used as an example to display the confusing error. Sometimes you need to work with various forms of data.

The point was that the error message was very obscure and confusing and I was just hoping that at least the error message could be more clear by saying "Associative Array value found, but an array is required" or interpret it as an object and say "Object found, but an array is required".

It doesn't really matter to me now since it's been so long and I've dealt with it somehow, but I still think my request was valid.

Perhaps minimally, the docs could give a disclaimer that associative arrays come with issues and are not recommended as values.
