### ISSUE TITLE
Default values don't get applied to objects inside of an array

### ISSUE THREAD

**Issue by pcjacobse** [jsonrainbow/json-schema#417] opened 2017-04-21 12:03 UTC
Hi,

It seems that the default values don't get applied to objects inside of an array.
It looks like that only the top level object gets their default values applied.

The validation in the sub-object does work (like type checking and required fields).

I'm running version 5.2.0

Example:
I expect the 'test' property to be filled with the default value if not present. 
```
$data = [
    (object)[
        "key" => 1,
        "test" => 1
    ],(object)[
        "key" => 1,
    ]
];
$validator = new \JsonSchema\Validator();

var_dump($validator->validate(
    $data,
    json_decode('
    {
        "type": "array",
        "items": [
            {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "integer"
                    },
                    "test": {
                        "type": "integer",
                        "default": 0
                    }
                },
                "required": [
                    "key"
                ]
            }
        ]
    }
    '), \JsonSchema\Constraints\Constraint::CHECK_MODE_APPLY_DEFAULTS
));
var_dump($data);
```

Gives: 
```
int(0)

array(2) {
  [0]=>
  object(stdClass)#3 (2) {
    ["key"]=>
    int(1)
    ["test"]=>
    int(1)
  }
  [1]=>
  object(stdClass)#2 (1) {
    ["key"]=>
    int(1)
  }
}
```

**Comment by erayd** [comment] 2017-04-21 22:52
@pcjacobse Thanks for reporting this.

I've found the root cause - the logic that prevents recursive application of defaults is being incorrectly triggered for arrays, with the result that the library thinks it has already applied the default value for `"test"` and skips it.

Currently thinking of the best way to address this.

**Comment by erayd** [comment] 2017-04-21 22:59
@mathroc Do you have an opinion?

The problem is the call to `$path->setFromDefault()` in the array section of `UndefinedConstraint::applyDefaultValues()`.  It needs to be called only for each element that has been set from a default, and *not* for the entire array the way it is now. However... we don't, at that point, actually have a path object for the array members - `$path` refers to the array itself.

Obviously this needs fixing, but it may require changing the recusion logic for defaults.

**Comment by mathroc** [comment] 2017-05-15 23:18
@erayd sorry I missed this, I’ll take a look at this in the next few days

**Comment by mathroc** [comment] 2017-05-19 14:57
@erayd this seems a bit tricky 😕 one think though, shouldn't `$path->setFromDefault();` be called at the end of the previous `if` (one line up) ?

it will still cause problems when default items are defined inside arrays but that's not the case in @pcjacobse exemple

**Comment by krismckay** [comment] 2017-08-29 22:09
@mathroc @erayd @pcjacobse 
I'm not sure if you guys have made any progress on this, but I made the following change and it appears to be working for me.
UndefinedConstraint.php:Line273
Add the following after the `$path->setFromDefault();`
`$this->applyDefaultValues($value[$currentItem], $schema->items[$currentItem], $path);`
Which is just recursively passing the array items through the same function. If this ends up blowing up on me I'll repost.

**Comment by erayd** [comment] 2017-08-30 02:54
@krismckay Line 273 of UndefinedConstraint.php (branch 6.0.0-dev) is `} else {`. Could you please clarify exactly where you're proposing that line be inserted? If you could include some of the surrounding code in your post for context, that would be helpful. I'm assuming that you probably meant to insert after L277.

Overall, I like the fundamental approach of your idea. The implementation as you've posted it isn't quite suitable (the path passed for recursion needs to be correct) - however, recursing within this block is a good idea, and seems like an ideal solution to the problem.

If you are intending to submit a PR for this, please base it on 6.0.0-dev, and address the issues above. If not, let me know, and I'll do a PR when I have the time.

**Comment by krismckay** [comment] 2017-08-30 13:49
@erayd Sorry, I should have mentioned the version.. I'm on version 5.2 rather then the dev build. Here's the patch I'm applying in my build process:
`--- ./vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php.orig  2017-08-29 17:12:10.000000000 -0500
+++ ./vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php       2017-08-29 17:12:18.000000000 -0500
@@ -272,4 +272,5 @@
                 }
                 $path->setFromDefault();
+                $this->applyDefaultValues($value[$currentItem], $schema->items[$currentItem], $path);
             }
         } elseif (
`

**Comment by krismckay** [comment] 2017-08-30 16:13
Hmm, that last "fix" only corrects the first item in an array. I have a new patch now that applies it to each item in the array. However, I've also found that the "CHECK_MODE_COERCE_TYPES" property is also affected by the same bug. It doesn't affect all items of an array. Hoping to get that working as well.
Here's the current patch to hit defaults for all array elements:
~~~~
--- vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php.orig    2017-08-29 17:29:54.000000000 -0500
+++ vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php 2017-08-30 10:42:00.000000000 -0500
@@ -261,16 +261,21 @@
             // $value is an array, and items are defined - treat as plain array
             foreach ($items as $currentItem => $itemDefinition) {
-                if (
-                    !array_key_exists($currentItem, $value)
-                    && property_exists($itemDefinition, 'default')
-                    && $this->shouldApplyDefaultValue($requiredOnly, $itemDefinition)) {
-                    if (is_object($itemDefinition->default)) {
-                        $value[$currentItem] = clone $itemDefinition->default;
-                    } else {
-                        $value[$currentItem] = $itemDefinition->default;
+                foreach($value as &$val){
+                    if (
+                        !array_key_exists($currentItem, $val)
+                        && property_exists($itemDefinition, 'default')
+                        && $this->shouldApplyDefaultValue($requiredOnly, $itemDefinition))
+                    {
+                        if (is_object($itemDefinition->default))
+                        {
+                            $val[$currentItem] = clone $itemDefinition->default;
+                        } else
+                        {
+                            $val[$currentItem] = $itemDefinition->default;
+                        }
                     }
+                    $path->setFromDefault();
+                    $this->applyDefaultValues($val, $schema->items[$currentItem], $path);
                 }
-                $path->setFromDefault();
-                $this->applyDefaultValues($value[$currentItem], $schema->items[$currentItem], $path);
             }
         } elseif (
~~~~

**Comment by DannyvdSluijs** [comment] 2024-07-22 18:12
Closing as reported to be a false alarm.

**Closed by DannyvdSluijs** 2024-07-22 18:12 UTC
