### ISSUE TITLE
PHP 8.4 warnings

### ISSUE THREAD

**Issue by matbech** [jsonrainbow/json-schema#730] opened 2024-07-06 12:26 UTC
PHP 8.4 issues the following warnings:
```
Deprecated: JsonSchema\Constraints\BaseConstraint::__construct(): Implicitly marking parameter $factory as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/BaseConstraint.php on line 41

Deprecated: JsonSchema\Constraints\BaseConstraint::addError(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/BaseConstraint.php on line 46

Deprecated: JsonSchema\Constraints\BaseConstraint::addError(): Implicitly marking parameter $more as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/BaseConstraint.php on line 46

Deprecated: JsonSchema\Constraints\Factory::__construct(): Implicitly marking parameter $schemaStorage as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Factory.php on line 76

Deprecated: JsonSchema\Constraints\Factory::__construct(): Implicitly marking parameter $uriRetriever as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Factory.php on line 76

Deprecated: JsonSchema\Constraints\Constraint::incrementPath(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php on line 42

Deprecated: JsonSchema\Constraints\Constraint::checkArray(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php on line 68

Deprecated: JsonSchema\Constraints\Constraint::checkObject(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php on line 86

Deprecated: JsonSchema\Constraints\Constraint::checkType(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php on line 103

Deprecated: JsonSchema\Constraints\Constraint::checkUndefined(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php on line 119

Deprecated: JsonSchema\Constraints\Constraint::checkString(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php on line 136

Deprecated: JsonSchema\Constraints\Constraint::checkNumber(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php on line 152

Deprecated: JsonSchema\Constraints\Constraint::checkEnum(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php on line 168

Deprecated: JsonSchema\Constraints\Constraint::checkFormat(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php on line 184

Deprecated: JsonSchema\Constraints\ConstraintInterface::addError(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/ConstraintInterface.php on line 43

Deprecated: JsonSchema\Constraints\ConstraintInterface::addError(): Implicitly marking parameter $more as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/ConstraintInterface.php on line 43

Deprecated: JsonSchema\Constraints\ConstraintInterface::check(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/ConstraintInterface.php on line 64

Deprecated: JsonSchema\SchemaStorage::__construct(): Implicitly marking parameter $uriRetriever as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php on line 19

Deprecated: JsonSchema\SchemaStorage::__construct(): Implicitly marking parameter $uriResolver as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php on line 19

Deprecated: JsonSchema\Constraints\SchemaConstraint::check(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/SchemaConstraint.php on line 31

Deprecated: JsonSchema\Constraints\UndefinedConstraint::check(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php on line 34

Deprecated: JsonSchema\Constraints\TypeConstraint::check(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/TypeConstraint.php on line 42

Deprecated: JsonSchema\Constraints\ObjectConstraint::check(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/ObjectConstraint.php on line 30

Deprecated: JsonSchema\Constraints\ObjectConstraint::validatePatternProperties(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/ObjectConstraint.php on line 54

Deprecated: JsonSchema\Constraints\ObjectConstraint::validateElement(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/ObjectConstraint.php on line 93

Deprecated: JsonSchema\Constraints\ObjectConstraint::validateProperties(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/ObjectConstraint.php on line 135

Deprecated: JsonSchema\Constraints\ObjectConstraint::validateMinMaxConstraint(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/ObjectConstraint.php on line 177

Deprecated: JsonSchema\Constraints\StringConstraint::check(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/StringConstraint.php on line 25

Deprecated: JsonSchema\Constraints\FormatConstraint::check(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/FormatConstraint.php on line 27

Deprecated: JsonSchema\Constraints\CollectionConstraint::check(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/CollectionConstraint.php on line 25

Deprecated: JsonSchema\Constraints\CollectionConstraint::validateItems(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/CollectionConstraint.php on line 64

Deprecated: JsonSchema\Constraints\EnumConstraint::check(): Implicitly marking parameter $path as nullable is deprecated, the explicit nullable type must be used instead in phar://composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/EnumConstraint.php on line 25
```

**Comment by Seldaek** [comment] 2024-07-06 20:14
Known issue, we're on it. Also duplicate of https://github.com/jsonrainbow/json-schema/pull/717 so closing

**Closed by Seldaek** 2024-07-06 20:14 UTC

**Comment by Seldaek** [comment] 2024-07-06 22:13
Just took care of this in 5.3.0
